bug fix for natural person validation
trisacrypto/testnet pull request #117
Opened 2023-02-15 19:32 UTC by DanielSollis

Adds a nil check before validating the natural person to prevent panics when the beneficiary contains a legal person.

2023-02-15 20:36 UTC, pdeziel reviewed
Thank you for updating the certs to fix the test! I just had one follow up question.

2023-02-15 20:36 UTC, pdeziel commented on pkg/rvasp/transfer.go
> +		if naturalPerson := identity.Beneficiary.BeneficiaryPersons[0].GetNaturalPerson(); naturalPerson != nil {
If natural person is nil do we also want to consider that an error? In other words is the beneficiary person required for a valid beneficiary?

2023-02-15 20:54 UTC, DanielSollis commented on pkg/rvasp/transfer.go
> +		if naturalPerson := identity.Beneficiary.BeneficiaryPersons[0].GetNaturalPerson(); naturalPerson != nil {
The issue here is that Krupa's identity had a legal person under `beneficiary_persons` and not a natural person, which if I'm correct is entirely valid IVMS101

2023-02-15 21:24 UTC, pdeziel commented on pkg/rvasp/transfer.go
> +		if naturalPerson := identity.Beneficiary.BeneficiaryPersons[0].GetNaturalPerson(); naturalPerson != nil {
Ok, here's what I propose. Let's make it a switch statement and check for either `NaturalPerson` or `LegalPerson`. In both of those cases validate the entity, otherwise return a validation error. That should correspond better to IVMS101. We should probably do the same for `BeneficiaryVASP` on line 250 while we're at it.

2023-02-16 01:39 UTC, DanielSollis commented on pkg/rvasp/transfer.go
> +		if naturalPerson := identity.Beneficiary.BeneficiaryPersons[0].GetNaturalPerson(); naturalPerson != nil {
That's a good idea, I implemented the changes, that should fix the issue

2023-02-16 14:59 UTC, pdeziel requested changes
Just one small change requested, basically I think we should throw a validation error if the beneficiary person or beneficiary vasp person does not match one of the expected types.

2023-02-16 14:59 UTC, pdeziel commented on pkg/rvasp/transfer.go
> +			}
I think we need a default case to handle the case where the beneficiary person is nil (or something that happens to fit the `isPerson_Person` interface but is not a `Person_NaturalPerson` or `Person_LegalPerson`).

See this example, if a nil object is type checked then the default case is triggered: https://go.dev/play/p/aHIX6AOtfJz

2023-02-16 14:59 UTC, pdeziel commented on pkg/rvasp/transfer.go
> +			}
Also add a default case here.

2023-02-16 15:02 UTC, pdeziel commented on pkg/rvasp/transfer.go
> +			}
Could you also create a follow up story to add a test for `validateIdentityPayload`? Specifically I want to make sure this fix avoids the panic.

2023-02-16 18:53 UTC, DanielSollis commented on pkg/rvasp/transfer.go
> +			}
Default added and story created

2023-02-16 20:43 UTC, pdeziel approved these changes
Awesome! I look forward to deploying it!

2023-02-16 20:44 UTC, merged